 
CREATE TABLE  `DrTuxTest`.`rpu_passages` (
  `rpu_encours_id_praticien` varchar(45) default NULL,
  `rpu_encours_id_ide` varchar(45) default NULL,
  `rpu_encours_id_dossier` varchar(45) default NULL,
  `rpu_encours_id_patient` varchar(45) default NULL,
  `rpu_encours_nom_prenom_patient` varchar(100) default NULL,
  `rpu_encours_dt_naissance_patient` date default NULL,
  `rpu_encours_sexe_patient` char(1) default NULL,
  `rpu_encours_dt_entree` datetime default NULL,
  `rpu_encours_dt_examen` datetime default NULL,
  `rpu_encours_dt_sortie` datetime default NULL,
  `rpu_encours_dt_lastUse` datetime default NULL,
  `rpu_encours_salle_examen` varchar(45) default NULL,
  `rpu_encours_categorie_recours` varchar(45) default NULL,
  `rpu_encours_motif_recours` varchar(200) default NULL,
  `rpu_encours_code_recours` varchar(10) default NULL,
  `rpu_encours_est_uhcd` tinyint(1) default '0',
  `rpu_encours_dt_uhcd` datetime default NULL,
  `rpu_rpu_blob` text,
  `rpu_xml_blob` text,
  `rpu_pk` int(11) NOT NULL auto_increment,
  PRIMARY KEY  (`rpu_pk`),
  KEY `rpu_encours_id_praticien_idx` (`rpu_encours_id_praticien`),
  KEY `rpu_encours_id_dossier_idx` (`rpu_encours_id_dossier`)
) ENGINE=MyISAM AUTO_INCREMENT=9839 DEFAULT CHARSET=latin1

CREATE TABLE  `DrTuxTest`.`het_passages` (
  `het_encours_id_praticien` varchar(45) default NULL,
  `het_encours_id_ide` varchar(45) default NULL,
  `het_encours_id_dossier` varchar(45) default NULL,
  `het_encours_id_patient` varchar(45) default NULL,
  `het_encours_nom_prenom_patient` varchar(100) default NULL,
  `het_encours_dt_naissance_patient` date default NULL,
  `het_encours_sexe_patient` char(1) default NULL,
  `het_encours_dt_entree` datetime default NULL,
  `het_encours_dt_examen` datetime default NULL,
  `het_encours_dt_sortie` datetime default NULL,
  `het_encours_dt_lastUse` datetime default NULL,
  `het_encours_salle_examen` varchar(45) default NULL,
  `het_encours_categorie_recours` varchar(45) default NULL,
  `het_encours_motif_recours` varchar(200) default NULL,
  `het_encours_code_recours` varchar(10) default NULL,
  `het_encours_est_uhcd` tinyint(1) default '0',
  `het_encours_dt_uhcd` datetime default NULL,
  `het_het_blob` text,
  `het_xml_blob` text,
  `het_pk` int(11) NOT NULL auto_increment,
  PRIMARY KEY  (`het_pk`),
  KEY `het_encours_id_praticien_idx` (`het_encours_id_praticien`),
  KEY `het_encours_id_dossier_idx` (`het_encours_id_dossier`)
) ENGINE=MyISAM AUTO_INCREMENT=9839 DEFAULT CHARSET=latin1